cask_args appdir: '/Applications'

brew 'atuin'
brew 'cloud-sql-proxy'
brew 'docker'
brew 'docker-compose'
brew 'eza'
brew 'imagemagick'
brew 'jq'
brew 'gh'
brew 'lazygit'
brew 'neovim'
brew 'postgresql@18'
brew 'spaceman-diff'
brew 'spark'
brew 'starship'
brew 'ripgrep'
brew 'wget'
brew 'yt-dlp'

cask 'docker-desktop'
cask 'istat-menus'
cask 'ghostty'
cask 'maccy'
cask 'obsidian'
cask 'slack'
cask 'sublime-text'
cask 'visual-studio-code'
cask 'vlc'
cask 'zoom'
